// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6r9q0Sq-E0iCGxtnUJewKxWz03jdJoE',
    appId: '1:688356585349:web:ab2838ef0e5a27976d5eec',
    messagingSenderId: '688356585349',
    projectId: 'chat-1b7a5',
    authDomain: 'chat-1b7a5.firebaseapp.com',
    storageBucket: 'chat-1b7a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASVsSaZrn33NM1nlkYGLyn0rZ41mkRsLc',
    appId: '1:688356585349:android:7068fd4e11ecd3fa6d5eec',
    messagingSenderId: '688356585349',
    projectId: 'chat-1b7a5',
    storageBucket: 'chat-1b7a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaprO9R7E5u9DSGVRyQx0jIGyPR43IYn0',
    appId: '1:688356585349:ios:dd33ba765fab2a066d5eec',
    messagingSenderId: '688356585349',
    projectId: 'chat-1b7a5',
    storageBucket: 'chat-1b7a5.appspot.com',
    iosClientId: '688356585349-7l044mmrd90leau3m7n546lcam9bi74d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaprO9R7E5u9DSGVRyQx0jIGyPR43IYn0',
    appId: '1:688356585349:ios:dd33ba765fab2a066d5eec',
    messagingSenderId: '688356585349',
    projectId: 'chat-1b7a5',
    storageBucket: 'chat-1b7a5.appspot.com',
    iosClientId: '688356585349-7l044mmrd90leau3m7n546lcam9bi74d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
